sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Fuellstand im Pelletsbehaelter"
    id: ${name}_Fuellstand_im_Pelletsbehaelter
    register_type: read
    address: 22
    unit_of_measurement: "%"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.0048309178743961

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Resetierbarer kg-Zaehler"
    id: ${name}_Resetierbarer_kg_Zaehler
    register_type: read
    address: 82
    unit_of_measurement: "kg"
    device_class: "weight"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Resetierbarer t-Zaehler"
    id: ${name}_Resetierbarer_t_Zaehler
    register_type: read
    address: 83
    unit_of_measurement: "t"
    device_class: "weight"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Pelletverbrauch Gesamt"
    id: ${name}_Pelletverbrauch_Gesamt
    register_type: read
    address: 84
    unit_of_measurement: "t"
    device_class: "weight"
    state_class: "measurement"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Pelletlager Restbestand"
    id: ${name}_Pelletlager_Restbestand
    register_type: holding
    address: 320
    unit_of_measurement: "t"
    device_class: "weight"
    state_class: "measurement"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
