sensor:  
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} HK1 - Vorlauf-Isttemperatur"
    id: ${name}_HK1_Vorlauf_Isttemperatur
    register_type: read
    address: 21
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD
    filters:
      - multiply: 0.5

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} HK1 - Vorlauf-Solltemperatur"
    id: ${name}_HK1_Vorlauf_Solltemperatur
    register_type: read
    address: 22
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD
    filters:
      - multiply: 0.5
