sensor:  
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Kesseltemperatur"
    id: ${name}_Kesseltemperatur
    register_type: read
    address: 0
    unit_of_measurement: "째C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD 
    filters:
      - multiply: 0.5

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Abgastemperatur"
    id: ${name}_Abgastemperatur
    register_type: read
    address: 1
    unit_of_measurement: "째C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD 

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Saugzug - Ansteuerung"
    id: ${name}_Saugzug_Ansteuerung
    register_type: read
    address: 15
    unit_of_measurement: "%"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Saugzugdrehzahl"
    id: ${name}_Saugzugdrehzahl
    register_type: read
    address: 7
    unit_of_measurement: "rpm"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Sauerstoffregler"
    id: ${name}_Sauerstoffregler
    register_type: read
    address: 14
    unit_of_measurement: "%"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Restsauerstoffgehalt"
    id: ${name}_Restsauerstoffgehalt
    register_type: read
    address: 3
    unit_of_measurement: "%"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Prim채rluft"
    id: ${name}_Primaerluft
    register_type: read
    address: 10
    unit_of_measurement: "%"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Sekund채rluft"
    id: ${name}_Sekundaerluft
    register_type: read
    address: 11
    unit_of_measurement: "%"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Betriebsstunden"
    id: ${name}_Betriebsstunden
    register_type: read
    address: 98
    unit_of_measurement: "h"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Stunden seit letzter Wartung"
    id: ${name}_Stunden_seit_letzter_Wartung
    register_type: read
    address: 213
    unit_of_measurement: "h"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Betriebsstunden in der Feuererhaltung"
    id: ${name}_Betriebsstunden_in_der_Feuererhaltung
    register_type: read
    address: 115
    unit_of_measurement: "h"
    value_type: U_WORD

binary_sensor:
  - platform: template
    name: "${name} Kesselzustand Heizen"
    id: ${name}_Kesselzustand_Heizen
    lambda: |-
      if (id(${name}_Kesselzustand).state == "Heizen") {
        return true;
      } else {
        return false;
      }
